-- SHADOWBLOX V2
-- Execute uma única vez no SQL Editor do Supabase.
-- Esta migration parte da estrutura que já contém profiles, categories, products,
-- orders, order_items, payment_receipts e chat_messages.

create extension if not exists pgcrypto;


-- Estrutura-base para permitir uso também em um projeto Supabase novo.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  avatar_url text,
  is_admin boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  category_id bigint references public.categories(id) on delete set null,
  name text not null,
  description text,
  image_path text,
  price_cents integer not null default 0 check (price_cents >= 0),
  old_price_cents integer check (old_price_cents is null or old_price_cents >= 0),
  stock integer not null default 0 check (stock >= 0),
  featured boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'awaiting_payment',
  payment_method text,
  total_cents integer not null default 0 check (total_cents >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id uuid references public.products(id) on delete set null,
  product_name text not null,
  quantity integer not null default 1 check (quantity > 0),
  unit_price_cents integer not null check (unit_price_cents >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.payment_receipts (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  file_path text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.chat_messages (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete cascade,
  message text,
  attachment_path text,
  read_at timestamptz,
  created_at timestamptz not null default now(),
  check (message is not null or attachment_path is not null)
);

-- =========================================================
-- 1. PERFIS, CARGOS E CONTROLE DE ACESSO
-- =========================================================

alter table public.profiles add column if not exists email text;
alter table public.profiles add column if not exists role text not null default 'customer';
alter table public.profiles add column if not exists blocked boolean not null default false;
alter table public.profiles add column if not exists blocked_reason text;
alter table public.profiles add column if not exists updated_at timestamptz not null default now();

alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles add constraint profiles_role_check
check (role in ('owner','admin','delivery_staff','customer'));

update public.profiles p
set email = u.email
from auth.users u
where p.id = u.id and p.email is null;

update public.profiles
set role = case
  when lower(coalesce(email,'')) = 'ffj6303@gmail.com' then 'owner'
  when coalesce(is_admin,false) then 'admin'
  else coalesce(role,'customer')
end;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id,email,full_name,avatar_url,role,blocked)
  values (
    new.id,
    new.email,
    coalesce(
      new.raw_user_meta_data->>'full_name',
      new.raw_user_meta_data->>'name',
      split_part(coalesce(new.email,'usuario'), '@', 1)
    ),
    coalesce(new.raw_user_meta_data->>'avatar_url', new.raw_user_meta_data->>'picture'),
    case when lower(coalesce(new.email,'')) = 'ffj6303@gmail.com' then 'owner' else 'customer' end,
    false
  )
  on conflict (id) do update set
    email = excluded.email,
    full_name = coalesce(public.profiles.full_name, excluded.full_name),
    avatar_url = coalesce(public.profiles.avatar_url, excluded.avatar_url),
    role = case
      when lower(coalesce(excluded.email,'')) = 'ffj6303@gmail.com' then 'owner'
      else public.profiles.role
    end,
    updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert or update of email, raw_user_meta_data on auth.users
for each row execute function public.handle_new_user();

create or replace function public.current_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select coalesce((select role from public.profiles where id = auth.uid()), 'customer');
$$;

create or replace function public.has_role(allowed_roles text[])
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.current_role() = any(allowed_roles);
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.has_role(array['owner','admin']);
$$;

-- =========================================================
-- 2. CATÁLOGO
-- =========================================================

alter table public.categories add column if not exists sort_order integer not null default 0;

alter table public.products add column if not exists slug text;
alter table public.products add column if not exists category_slug text;
alter table public.products add column if not exists visible boolean not null default true;
alter table public.products add column if not exists out_of_stock boolean not null default false;
alter table public.products add column if not exists is_new boolean not null default false;
alter table public.products add column if not exists sort_order integer not null default 0;
alter table public.products add column if not exists updated_at timestamptz not null default now();

create unique index if not exists products_slug_key on public.products(slug);
create index if not exists products_category_slug_idx on public.products(category_slug);

insert into public.categories (name,slug,active,sort_order)
values
  ('Novo','novo',true,10),
  ('Combos','combos',true,20),
  ('Contas','contas',true,30),
  ('Gamepass','gamepass',true,40),
  ('Sets (Estilos de luta) - Personagens','sets',true,50),
  ('Upgrade - Ascensões & B10','upgrades',true,60),
  ('Set Relíquias','reliquias',true,70),
  ('Rerolls','rerolls',true,80),
  ('Caixas','caixas',true,90)
on conflict (slug) do update set
  name = excluded.name,
  active = excluded.active,
  sort_order = excluded.sort_order;

update public.products p
set category_slug = c.slug
from public.categories c
where p.category_id = c.id and p.category_slug is null;

-- Produtos iniciais. Imagens permanecem dentro da pasta assets do projeto.
insert into public.products
(slug,name,description,image_path,price_cents,old_price_cents,stock,featured,active,visible,out_of_stock,is_new,category_slug,category_id,sort_order)
select v.slug,v.name,v.description,v.image_path,v.price_cents,v.old_price_cents,v.stock,v.featured,true,true,false,v.is_new,v.category_slug,c.id,v.sort_order
from (values
  ('cla-rerolls','Clã Rerolls (10k - 30k - 70k)','Entrega assistida','assets/products/cla-rerolls.jpg',870,null,999,true,false,'rerolls',10),
  ('race-rerolls','Race Rerolls (100k - 500k - 1M)','Entrega assistida','assets/products/race-rerolls.jpg',950,null,999,true,false,'rerolls',20),
  ('trait-rerolls','Trait Rerolls (100k - 500k - 1M)','Entrega assistida','assets/products/trait-rerolls.jpg',982,null,999,false,false,'rerolls',30),
  ('passive-rerolls','Passive Rerolls (100k - 500k - 1M)','Entrega assistida','assets/products/passive-rerolls.jpg',935,null,999,false,false,'rerolls',40),
  ('power-shard','Power Shard (50k - 300k - 500k)','Entrega assistida','assets/products/power-shard.jpg',940,null,999,false,false,'rerolls',50),
  ('rimuru','Rimuru (Estilo de luta)','Entrega assistida','assets/products/rimuru.jpg',953,null,999,true,false,'sets',60),
  ('true-aizen','True Aizen V2 + F (Estilo de luta)','Entrega assistida','assets/products/true-aizen.jpg',953,3200,999,true,false,'sets',70),
  ('kokushibo','Kokushibo + F Set (Estilo de luta)','Entrega assistida','assets/products/kokushibo.jpg',953,3000,999,false,false,'sets',80),
  ('saber-alt','Saber Alt + F Set (Estilo de luta)','Entrega assistida','assets/products/saber-alt.jpg',954,2700,999,false,false,'sets',90),
  ('gilgamesh-set','Gilgamesh + F Set (Estilo de luta)','Entrega assistida','assets/products/gilgamesh-set.jpg',953,2600,999,false,false,'sets',100),
  ('madara-set','Madara + F Set (Estilo de luta)','Entrega assistida','assets/products/madara-set.jpg',953,2900,999,false,false,'sets',110),
  ('atomic-v2-set','Atomic V2 Set (Estilo de luta)','Entrega assistida','assets/products/atomic-v2-set.jpg',1000,2600,999,false,false,'sets',120),
  ('dio-brando','Dio Brando (The World)','Entrega assistida','assets/products/dio-brando.jpg',1420,2500,999,false,false,'sets',130),
  ('ice-queen','Lançamento Ice Queen','Entrega assistida','assets/products/ice-queen.jpg',1300,5000,999,false,false,'sets',140),
  ('ragna','Limited Ragna - Top 1','Entrega assistida','assets/products/ragna.jpg',3720,20000,999,false,false,'sets',150),
  ('madoka','Madoka Set (Top 2 Estilo de luta)','Entrega assistida','assets/products/madoka.jpg',3000,15000,999,false,false,'sets',160),
  ('cartheliya','Cartheliya + F (Estilo de luta)','Entrega assistida','assets/products/cartheliya.jpg',953,1900,999,false,false,'sets',170),
  ('gojo','Gojo + F (Estilo de luta)','Entrega assistida','assets/products/gojo.jpg',953,2200,999,false,false,'sets',180),
  ('atomic-b10','Atomic V2 + B10 + Título','Entrega assistida','assets/products/atomic-b10.jpg',2550,5000,999,false,false,'upgrades',190),
  ('gilgamesh-b10','Gilgamesh + F Set + B10 + Título','Entrega assistida','assets/products/gilgamesh-b10.jpg',2750,5000,999,false,false,'upgrades',200),
  ('2x-drops','2X Drops (Gamepass)','Entrega assistida','assets/products/2x-drops.jpg',920,1500,999,true,false,'gamepass',210),
  ('2x-luck','2X Luck (Gamepass)','Entrega assistida','assets/products/2x-luck.jpg',920,2000,999,true,false,'gamepass',220),
  ('combo-personagens','Exdeath + Madara + Atomic + Kokushibo Set','Entrega assistida','assets/products/combo-personagens.jpg',3520,8000,999,true,false,'combos',230),
  ('combo-caixas','300 Cosmetic Crates + 300 Auras Crates','Entrega assistida','assets/products/combo-caixas.jpg',1720,5000,999,true,false,'combos',240),
  ('spirit-key','Spirit Key','Entrega assistida','assets/products/spirit-key.jpg',950,null,999,true,true,'reliquias',250),
  ('spirit-stone','Spirit Stone','Entrega assistida','assets/products/spirit-stone.jpg',950,null,999,true,true,'reliquias',260),
  ('cosmic-being','Set Cosmic Being (Garou)','Entrega assistida','assets/products/cosmic-being.jpg',1350,null,999,true,true,'reliquias',270),
  ('sun-god-yoriichi','Set Sun God (Yoriichi)','Entrega assistida','assets/products/sun-god-yoriichi.jpg',1250,2500,999,true,true,'sets',280),
  ('black-reaper','Black Reaper (Kaneki)','Entrega assistida','assets/products/black-reaper.jpg',1200,2500,999,true,true,'sets',290)
) as v(slug,name,description,image_path,price_cents,old_price_cents,stock,featured,is_new,category_slug,sort_order)
join public.categories c on c.slug = v.category_slug
on conflict (slug) do nothing;

-- =========================================================
-- 3. PEDIDOS, ENTREGA E CHAT
-- =========================================================

alter table public.orders add column if not exists customer_name text;
alter table public.orders add column if not exists customer_email text;
alter table public.orders add column if not exists assigned_to uuid references public.profiles(id) on delete set null;
alter table public.orders add column if not exists assigned_at timestamptz;
alter table public.orders add column if not exists delivered_at timestamptz;
alter table public.orders add column if not exists internal_note text;

alter table public.orders drop constraint if exists orders_status_check;
alter table public.orders add constraint orders_status_check check (status in (
  'awaiting_payment','under_review','paid','rejected','in_service','delivered','cancelled','refunded'
));

alter table public.chat_messages drop constraint if exists chat_messages_message_check;
alter table public.chat_messages add constraint chat_messages_message_check
check (message is not null or attachment_path is not null);

create index if not exists orders_user_id_idx on public.orders(user_id);
create index if not exists orders_assigned_to_idx on public.orders(assigned_to);
create index if not exists orders_status_idx on public.orders(status);
create index if not exists chat_messages_order_id_idx on public.chat_messages(order_id);

create table if not exists public.admin_audit_logs (
  id uuid primary key default gen_random_uuid(),
  actor_id uuid references public.profiles(id) on delete set null,
  actor_role text,
  action text not null,
  entity_type text not null,
  entity_id text,
  old_data jsonb,
  new_data jsonb,
  reason text,
  created_at timestamptz not null default now()
);

create or replace function public.log_admin_action(
  p_action text,
  p_entity_type text,
  p_entity_id text,
  p_old_data jsonb default null,
  p_new_data jsonb default null,
  p_reason text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.admin_audit_logs(actor_id,actor_role,action,entity_type,entity_id,old_data,new_data,reason)
  values(auth.uid(),public.current_role(),p_action,p_entity_type,p_entity_id,p_old_data,p_new_data,p_reason);
end;
$$;


create or replace function public.audit_product_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op='INSERT' then
    perform public.log_admin_action('product_insert','product',new.id::text,null,to_jsonb(new),null);
    return new;
  elsif tg_op='UPDATE' then
    perform public.log_admin_action('product_update','product',new.id::text,to_jsonb(old),to_jsonb(new),null);
    return new;
  else
    perform public.log_admin_action('product_delete','product',old.id::text,to_jsonb(old),null,null);
    return old;
  end if;
end;
$$;

drop trigger if exists audit_product_change_trigger on public.products;
create trigger audit_product_change_trigger
after insert or update or delete on public.products
for each row execute function public.audit_product_change();

create or replace function public.can_access_order(p_order_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(
    select 1 from public.orders o
    where o.id = p_order_id and (
      o.user_id = auth.uid()
      or public.has_role(array['owner','admin'])
      or (
        public.current_role() = 'delivery_staff'
        and o.status in ('paid','in_service','delivered')
        and (o.assigned_to is null or o.assigned_to = auth.uid())
      )
    )
  );
$$;

create or replace function public.can_chat_order(p_order_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(
    select 1 from public.orders o
    where o.id = p_order_id
      and o.status in ('paid','in_service','delivered')
      and (
        o.user_id = auth.uid()
        or public.has_role(array['owner','admin'])
        or (public.current_role() = 'delivery_staff' and o.assigned_to = auth.uid())
      )
  );
$$;

create or replace function public.create_order(p_payment_method text, p_items jsonb)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order_id uuid := gen_random_uuid();
  v_item jsonb;
  v_product public.products%rowtype;
  v_quantity integer;
  v_total integer := 0;
  v_profile public.profiles%rowtype;
begin
  if auth.uid() is null then raise exception 'Faça login para finalizar a compra'; end if;
  if p_payment_method not in ('pix','card') then raise exception 'Forma de pagamento inválida'; end if;
  if jsonb_array_length(p_items) = 0 then raise exception 'Carrinho vazio'; end if;

  select * into v_profile from public.profiles where id = auth.uid();
  if coalesce(v_profile.blocked,false) then raise exception 'Conta bloqueada'; end if;

  insert into public.orders(id,user_id,customer_name,customer_email,status,payment_method,total_cents)
  values(v_order_id,auth.uid(),v_profile.full_name,v_profile.email,'awaiting_payment',p_payment_method,0);

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    v_quantity := greatest(1, least(100, coalesce((v_item->>'quantity')::integer,1)));
    select * into v_product from public.products where id = (v_item->>'product_id')::uuid for share;
    if not found then raise exception 'Produto não encontrado'; end if;
    if not v_product.active or not v_product.visible or v_product.out_of_stock or v_product.stock < v_quantity then
      raise exception 'Produto indisponível: %', v_product.name;
    end if;
    v_total := v_total + (v_product.price_cents * v_quantity);
    insert into public.order_items(order_id,product_id,product_name,quantity,unit_price_cents)
    values(v_order_id,v_product.id,v_product.name,v_quantity,v_product.price_cents);
  end loop;

  update public.orders set total_cents = v_total, updated_at = now() where id = v_order_id;
  return v_order_id;
exception when others then
  delete from public.orders where id = v_order_id;
  raise;
end;
$$;

create or replace function public.submit_payment_receipt(p_order_id uuid, p_file_path text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists(select 1 from public.orders where id=p_order_id and user_id=auth.uid()) then
    raise exception 'Pedido não encontrado';
  end if;
  insert into public.payment_receipts(order_id,user_id,file_path)
  values(p_order_id,auth.uid(),p_file_path)
  on conflict do nothing;
  update public.orders set status='under_review',updated_at=now() where id=p_order_id and user_id=auth.uid();
end;
$$;

create or replace function public.set_order_status(p_order_id uuid, p_status text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare v_old public.orders%rowtype;
begin
  if not public.has_role(array['owner','admin']) then raise exception 'Acesso negado'; end if;
  if p_status not in ('under_review','paid','rejected','cancelled','refunded') then raise exception 'Status inválido'; end if;
  select * into v_old from public.orders where id=p_order_id;
  update public.orders set status=p_status,updated_at=now() where id=p_order_id;
  perform public.log_admin_action('order_status','order',p_order_id::text,to_jsonb(v_old),jsonb_build_object('status',p_status),null);
  if p_status='paid' and not exists(select 1 from public.chat_messages where order_id=p_order_id) then
    insert into public.chat_messages(order_id,sender_id,message)
    values(p_order_id,auth.uid(),'Pagamento aprovado! Mande uma mensagem para receber o item.');
  end if;
end;
$$;

create or replace function public.claim_order(p_order_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare v_order public.orders%rowtype;
begin
  if not public.has_role(array['owner','admin','delivery_staff']) then raise exception 'Acesso negado'; end if;
  select * into v_order from public.orders where id=p_order_id for update;
  if v_order.status not in ('paid','in_service') then raise exception 'Pedido não está disponível para atendimento'; end if;
  if v_order.assigned_to is not null and v_order.assigned_to <> auth.uid() and public.current_role()='delivery_staff' then
    raise exception 'Este pedido já foi assumido por outro funcionário';
  end if;
  update public.orders set assigned_to=coalesce(assigned_to,auth.uid()),assigned_at=coalesce(assigned_at,now()),status='in_service',updated_at=now() where id=p_order_id;
  perform public.log_admin_action('claim_order','order',p_order_id::text,to_jsonb(v_order),jsonb_build_object('assigned_to',auth.uid(),'status','in_service'),null);
end;
$$;

create or replace function public.mark_order_delivered(p_order_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare v_order public.orders%rowtype;
begin
  select * into v_order from public.orders where id=p_order_id for update;
  if not (
    public.has_role(array['owner','admin'])
    or (public.current_role()='delivery_staff' and v_order.assigned_to=auth.uid())
  ) then raise exception 'Acesso negado'; end if;
  if v_order.status not in ('paid','in_service') then raise exception 'Pedido não pode ser entregue neste status'; end if;
  update public.orders set status='delivered',delivered_at=now(),updated_at=now() where id=p_order_id;
  perform public.log_admin_action('deliver_order','order',p_order_id::text,to_jsonb(v_order),jsonb_build_object('status','delivered'),null);
end;
$$;

-- =========================================================
-- 4. AVALIAÇÕES
-- =========================================================

create table if not exists public.store_reviews (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  order_id uuid not null unique references public.orders(id) on delete cascade,
  rating integer not null check (rating between 1 and 5),
  comment text not null check (char_length(comment) between 3 and 800),
  status text not null default 'published' check (status in ('published','hidden','flagged','removed')),
  moderation_reason text,
  moderated_by uuid references public.profiles(id) on delete set null,
  moderated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.review_responses (
  id uuid primary key default gen_random_uuid(),
  review_id uuid not null unique references public.store_reviews(id) on delete cascade,
  author_id uuid not null references public.profiles(id) on delete cascade,
  message text not null check (char_length(message) between 1 and 800),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists store_reviews_status_idx on public.store_reviews(status);
create index if not exists store_reviews_created_at_idx on public.store_reviews(created_at desc);

create or replace function public.get_public_reviews()
returns table(
  id uuid,
  rating integer,
  comment text,
  status text,
  created_at timestamptz,
  display_name text,
  avatar_url text,
  response_message text
)
language sql
stable
security definer
set search_path = public
as $$
  select r.id,r.rating,r.comment,r.status,r.created_at,
         coalesce(p.full_name,'Cliente') as display_name,
         p.avatar_url,
         rr.message as response_message
  from public.store_reviews r
  join public.profiles p on p.id=r.user_id
  left join public.review_responses rr on rr.review_id=r.id
  where r.status='published'
  order by r.created_at desc;
$$;

create or replace function public.get_eligible_review_orders()
returns table(order_id uuid, delivered_at timestamptz)
language sql
stable
security definer
set search_path = public
as $$
  select o.id,o.delivered_at
  from public.orders o
  where o.user_id=auth.uid()
    and o.status='delivered'
    and not exists(select 1 from public.store_reviews r where r.order_id=o.id)
  order by o.delivered_at desc;
$$;

create or replace function public.respond_to_review(p_review_id uuid, p_message text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.has_role(array['owner','admin']) then raise exception 'Acesso negado'; end if;
  insert into public.review_responses(review_id,author_id,message)
  values(p_review_id,auth.uid(),p_message)
  on conflict (review_id) do update set author_id=auth.uid(),message=excluded.message,updated_at=now();
  perform public.log_admin_action('review_response','review',p_review_id::text,null,jsonb_build_object('message',p_message),null);
end;
$$;

create or replace function public.toggle_review_visibility(p_review_id uuid, p_reason text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare v_old public.store_reviews%rowtype; v_new_status text;
begin
  if not public.has_role(array['owner','admin']) then raise exception 'Acesso negado'; end if;
  select * into v_old from public.store_reviews where id=p_review_id;
  v_new_status := case when v_old.status='published' then 'hidden' else 'published' end;
  update public.store_reviews set status=v_new_status,moderation_reason=p_reason,moderated_by=auth.uid(),moderated_at=now(),updated_at=now() where id=p_review_id;
  perform public.log_admin_action('review_moderation','review',p_review_id::text,to_jsonb(v_old),jsonb_build_object('status',v_new_status),p_reason);
end;
$$;

-- =========================================================
-- 5. FUNÇÕES DO PROPRIETÁRIO
-- =========================================================

create or replace function public.set_user_role(p_user_id uuid, p_role text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare v_old public.profiles%rowtype;
begin
  if public.current_role() <> 'owner' then raise exception 'Somente o proprietário pode alterar cargos'; end if;
  if p_role not in ('admin','delivery_staff','customer') then raise exception 'Cargo inválido'; end if;
  select * into v_old from public.profiles where id=p_user_id;
  if v_old.role='owner' then raise exception 'O proprietário não pode ser rebaixado'; end if;
  update public.profiles set role=p_role,is_admin=(p_role='admin'),updated_at=now() where id=p_user_id;
  perform public.log_admin_action('set_role','profile',p_user_id::text,to_jsonb(v_old),jsonb_build_object('role',p_role),null);
end;
$$;

create or replace function public.set_user_blocked(p_user_id uuid, p_blocked boolean, p_reason text default null)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare v_old public.profiles%rowtype;
begin
  if public.current_role() <> 'owner' then raise exception 'Somente o proprietário pode bloquear usuários'; end if;
  select * into v_old from public.profiles where id=p_user_id;
  if v_old.role='owner' then raise exception 'O proprietário não pode ser bloqueado'; end if;
  update public.profiles set blocked=p_blocked,blocked_reason=case when p_blocked then p_reason else null end,updated_at=now() where id=p_user_id;
  perform public.log_admin_action('set_blocked','profile',p_user_id::text,to_jsonb(v_old),jsonb_build_object('blocked',p_blocked),p_reason);
end;
$$;

-- =========================================================
-- 6. RLS
-- =========================================================

alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.payment_receipts enable row level security;
alter table public.chat_messages enable row level security;
alter table public.store_reviews enable row level security;
alter table public.review_responses enable row level security;
alter table public.admin_audit_logs enable row level security;

-- Remove políticas anteriores conhecidas.
drop policy if exists "User reads own profile" on public.profiles;
drop policy if exists "User updates own profile" on public.profiles;
drop policy if exists "Public reads categories" on public.categories;
drop policy if exists "Admins manage categories" on public.categories;
drop policy if exists "Public reads products" on public.products;
drop policy if exists "Admins manage products" on public.products;
drop policy if exists "Users read own orders" on public.orders;
drop policy if exists "Users create own orders" on public.orders;
drop policy if exists "Admins update orders" on public.orders;
drop policy if exists "Users read own order items" on public.order_items;
drop policy if exists "Users add own order items" on public.order_items;
drop policy if exists "Users read own receipts" on public.payment_receipts;
drop policy if exists "Users create own receipts" on public.payment_receipts;
drop policy if exists "Order members read chat" on public.chat_messages;
drop policy if exists "Order members send messages" on public.chat_messages;

create policy "profiles own or management reads"
on public.profiles for select to authenticated
using (id=auth.uid() or public.has_role(array['owner','admin']));

create policy "profiles user updates basic data"
on public.profiles for update to authenticated
using (id=auth.uid())
with check (id=auth.uid() and role=public.current_role());

create policy "categories public read"
on public.categories for select to anon,authenticated
using (active=true or public.has_role(array['owner','admin']));

create policy "categories admin manage"
on public.categories for all to authenticated
using (public.has_role(array['owner','admin']))
with check (public.has_role(array['owner','admin']));

create policy "products public read visible"
on public.products for select to anon,authenticated
using ((active=true and visible=true) or public.has_role(array['owner','admin']));

create policy "products admin manage"
on public.products for all to authenticated
using (public.has_role(array['owner','admin']))
with check (public.has_role(array['owner','admin']));

create policy "orders permitted read"
on public.orders for select to authenticated
using (public.can_access_order(id));

create policy "orders staff update"
on public.orders for update to authenticated
using (public.has_role(array['owner','admin']))
with check (public.has_role(array['owner','admin']));

create policy "order items permitted read"
on public.order_items for select to authenticated
using (public.can_access_order(order_id));

create policy "receipts own or finance staff read"
on public.payment_receipts for select to authenticated
using (user_id=auth.uid() or public.has_role(array['owner','admin']));

create policy "chat permitted read"
on public.chat_messages for select to authenticated
using (public.can_chat_order(order_id));

create policy "chat permitted insert"
on public.chat_messages for insert to authenticated
with check (sender_id=auth.uid() and public.can_chat_order(order_id));

create policy "reviews public read published"
on public.store_reviews for select to anon,authenticated
using (status='published' or user_id=auth.uid() or public.has_role(array['owner','admin']));

create policy "reviews verified insert"
on public.store_reviews for insert to authenticated
with check (
  user_id=auth.uid()
  and exists(select 1 from public.orders o where o.id=order_id and o.user_id=auth.uid() and o.status='delivered')
);

create policy "reviews owner edit seven days"
on public.store_reviews for update to authenticated
using (user_id=auth.uid() and created_at > now()-interval '7 days')
with check (user_id=auth.uid());

create policy "review responses public read"
on public.review_responses for select to anon,authenticated
using (exists(select 1 from public.store_reviews r where r.id=review_id and r.status='published') or public.has_role(array['owner','admin']));

create policy "audit owner read"
on public.admin_audit_logs for select to authenticated
using (public.current_role()='owner');

-- =========================================================
-- 7. STORAGE
-- =========================================================

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values
('product-images','product-images',true,10485760,array['image/jpeg','image/png','image/webp']),
('receipts','receipts',false,10485760,array['image/jpeg','image/png','image/webp','application/pdf']),
('chat-attachments','chat-attachments',false,10485760,array['image/jpeg','image/png','image/webp','application/pdf'])
on conflict (id) do update set
  public=excluded.public,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;

drop policy if exists "Admins upload product images" on storage.objects;
drop policy if exists "Admins update product images" on storage.objects;
drop policy if exists "Admins delete product images" on storage.objects;
drop policy if exists "Users upload own receipts" on storage.objects;
drop policy if exists "Users read own receipts files" on storage.objects;

create policy "staff manage product images"
on storage.objects for all to authenticated
using (bucket_id='product-images' and public.has_role(array['owner','admin']))
with check (bucket_id='product-images' and public.has_role(array['owner','admin']));

create policy "user uploads own receipt"
on storage.objects for insert to authenticated
with check (bucket_id='receipts' and (storage.foldername(name))[1]=auth.uid()::text);

create policy "user or finance reads receipt"
on storage.objects for select to authenticated
using (bucket_id='receipts' and ((storage.foldername(name))[1]=auth.uid()::text or public.has_role(array['owner','admin'])));

create policy "order members manage chat attachments"
on storage.objects for all to authenticated
using (bucket_id='chat-attachments')
with check (bucket_id='chat-attachments');

-- =========================================================
-- 8. GRANTS E REALTIME
-- =========================================================

grant usage on schema public to anon,authenticated;
grant select on public.categories,public.products to anon,authenticated;
grant select on public.store_reviews,public.review_responses to anon,authenticated;
grant select on public.profiles to authenticated;
grant update(full_name,avatar_url,updated_at) on public.profiles to authenticated;
grant select,insert,update,delete on public.categories,public.products to authenticated;
grant select on public.orders,public.order_items,public.payment_receipts,public.chat_messages,public.admin_audit_logs to authenticated;
grant insert on public.chat_messages,public.store_reviews to authenticated;
grant update(rating,comment,updated_at) on public.store_reviews to authenticated;
grant execute on function public.create_order(text,jsonb) to authenticated;
grant execute on function public.submit_payment_receipt(uuid,text) to authenticated;
grant execute on function public.set_order_status(uuid,text) to authenticated;
grant execute on function public.claim_order(uuid) to authenticated;
grant execute on function public.mark_order_delivered(uuid) to authenticated;
grant execute on function public.get_public_reviews() to anon,authenticated;
grant execute on function public.get_eligible_review_orders() to authenticated;
grant execute on function public.respond_to_review(uuid,text) to authenticated;
grant execute on function public.toggle_review_visibility(uuid,text) to authenticated;
grant execute on function public.set_user_role(uuid,text) to authenticated;
grant execute on function public.set_user_blocked(uuid,boolean,text) to authenticated;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname='supabase_realtime' and schemaname='public' and tablename='chat_messages'
  ) then
    execute 'alter publication supabase_realtime add table public.chat_messages';
  end if;
end $$;

-- Atualiza o proprietário no final para garantir o acesso.
update public.profiles set role='owner',is_admin=true,blocked=false,updated_at=now()
where lower(coalesce(email,''))='ffj6303@gmail.com';
